### ISSUE TITLE
List all districts

### ISSUE THREAD

**Issue by AriHrannar** [veritus/veritus-web#10]
Call get all on api and list all districts

**Comment by Ragnar-Hardarson** [comment]
Is this for admin purposes?

**Comment by AriHrannar** [comment]
No, I was thinking it might be nice to have a list of all the districts. Users could then click their own for example and see what politicians are in which district. Dont think there is a webservice for that though but might be a good feature :)

**Comment by Ragnar-H** [comment]
Closed with #43
