### ISSUE TITLE
List all promises

### ISSUE THREAD

**Issue by AriHrannar** [veritus/veritus-web#14]
Call API and list all promises

**Comment by Ragnar-Hardarson** [comment]
@AriHrannar could you elaborate on the use case for this list?

How is this different from listing the promises beneath the politicians?

**Comment by AriHrannar** [comment]
Probably not that helpful to see a list of promises when I think of it. Likely be more useful to see it under politicians / political parties like you say.

**Comment by Ragnar-Hardarson** [comment]
I guess this brings up a bigger issue I'm having.

I'm lacking the `Vision` we're working towards. A rough idea of how the App should look in its MVP status.

Some rough sketches and a collection of use cases would be invaluable for me. But I'm out of my depth when it comes to using the App.
@AriHrannar & @Jarngreipr would you be willing to give me some guidance here?

**Comment by Ragnar-H** [comment]
Turns out listing all `Promises` is valuable for Admin purposes.

This'll probably be some sort of table.
- Doesn't need to be pretty
- Admin needs good overview
- Admin can take actions from this screen

**Comment by skabbi** [comment]
@Ragnar-H would the promises be sorted by political party?

**Comment by AriHrannar** [comment]
Not entirely sure what you mean sorted/tagged by political parties :)

Currently a ```Promise``` is related to either a Politician or a Political Party. 

@Ragnar-H is thinking of doing something like [DataTables](https://datatables.net/index) to list all of these Promises. Not using Jquery  like that link but that website is a good example of what we mean by "DataTable".

One of the features of a "DataTable" is sorting / filtering so if thats what you mean, then it should be possible to sort and filter by political party.

However, each ```Promise``` will also have multiple ```Subjects``` (think tags). These might be "Healthcare", "Construction", "Roads", "Aluminum", whatever. 

We will then use these ```Subjects``` to try and find ```Cases``` on althingi that match the ```Promise```. So if a ```Case``` and a ```Promise``` both have 10 ```Subjects``` and 9 of them are the same, its likely that they are related. 

Does that make sense?

**Comment by Ragnar-H** [comment]
What this guy said ☝️

I'll probably use this http://www.material-ui.com/#/components/table
Stay lean, use what we got, MVP, first to market... All that jazz. 

Then expand upon it later if we feel the need. 

@skarpi the important thing that @arihrannar mentioned here above are the Subjects. 
It's this mapping between Cases and Promises (and thereby Politicians or Parties) that is value proposition of this Product

**Comment by skarpi** [comment]
@Ragnar-H Nice typo :)

**Comment by Ragnar-H** [comment]
Haha, sorry man

**Comment by skabbi** [comment]
@AriHrannar Sorry for being unclear, I was just wondering how you were planning on displaying this to the user since it was not specified in any way. My first impression was that a wall of promises would just appear, e.g.
- Promise 1
- Promise 2
- Promise 3

without any context of who made the promise.

Using a DataTable sounds good since it should make it easy to sort and group by subject or parties.

Btw, though I don't have the same vision for this as you do, I do think having a single place with all the promises would be a good idea. It gives new users a place to start when looking over what the parties are offering. Also feels it would be a more unbiased environment than if going to parties page for undecided voters.

**Comment by AriHrannar** [comment]
Yeah that is a valid point. I could see undecided voters wanting to see all promises

**Comment by Ragnar-H** [comment]
> Btw, though I don't have the same vision for this as you do, I do think having a single place with all the promises would be a good idea. It gives new users a place to start when looking over what the parties are offering. Also feels it would be a more unbiased environment than if going to parties page for undecided voters.

I think this is a valid point.
But we need to keep in mind that we shouldn't try to support every use case before we launch, then we'll never be finished.

In my mind there is no question that Admins need and overview of promises, and the ability to take bulk actions on them.
Datatables are perfect for this.

But datatables are enterprise-y and not friendly toward "normal" users.
So the PR I've got lined up will be for Admin purposes.


Also in my mind™, the sketches outlined in https://github.com/veritus/veritus-web/issues/39 cover 80% of use cases for normal users. So I want to shoot for those in the first round and get some non-techies to click around.
The sketches are just missing Admin actions, which are sorely needed in this case.

**Comment by Ragnar-H** [comment]
Closing this with the pretty-ass-table

<img width="1792" alt="screen shot 2018-03-03 at 15 40 33" src="https://user-images.githubusercontent.com/22854722/36935531-39bcbdf4-1ef9-11e8-8fb2-a6413d31de34.png">
