### ISSUE TITLE
Sidebar does not close on click

### ISSUE THREAD

**Issue by Jarngreipr** [veritus/veritus-web#25]
![sidebar](https://cloud.githubusercontent.com/assets/7809566/26365985/9c09d518-3fe9-11e7-99fb-b1f2673c7905.gif)

The sidebar stays open when f. example Add Promise is clicked. This requires an unnecessary click from the user and should be made automatic.

**Comment by AriHrannar** [comment]
![issue](https://cloud.githubusercontent.com/assets/6696198/26365270/689d3078-3fe7-11e7-9045-1f3120b52891.gif)

**Comment by Ragnar-Hardarson** [comment]
Additionally it does not redirect unless the text is selected
![doesnt-route](https://cloud.githubusercontent.com/assets/22854722/26374406/8d3e6b36-4005-11e7-9986-f5e64041bc05.gif)
